#!/bin/sh
set -eu

# Generate env-config.js
cat <<EOF > /usr/share/nginx/html/env-config.js
window.env = {
  VITE_SERVER_URL: "${VITE_SERVER_URL:-/}",
  VITE_HLS_BASE_URL: "${VITE_HLS_BASE_URL:-/hls}",
  VITE_API_BASE_URL: "${VITE_API_BASE_URL:-/api}",
  VITE_RTMP_SERVER_URL: "${VITE_RTMP_SERVER_URL:-rtmp://localhost/live}",
  VITE_MOBILE_DEFAULT_SERVER_URL: "${VITE_MOBILE_DEFAULT_SERVER_URL:-https://datasetto.com}",
  VITE_MOBILE_DEFAULT_HLS_URL: "${VITE_MOBILE_DEFAULT_HLS_URL:-https://datasetto.com/hls}",
  VITE_MOBILE_DEFAULT_RTMP_URL: "${VITE_MOBILE_DEFAULT_RTMP_URL:-rtmp://datasetto.com/live}",
  VITE_WEBRTC_ICE_SERVERS: '${VITE_WEBRTC_ICE_SERVERS:-}',
  VITE_TURN_URL: "${VITE_TURN_URL:-}",
  VITE_TURN_USERNAME: "${VITE_TURN_USERNAME:-}",
  VITE_TURN_CREDENTIAL: "${VITE_TURN_CREDENTIAL:-}",
  VITE_VOICE_OPUS_BITRATE: "${VITE_VOICE_OPUS_BITRATE:-64000}",
  VITE_VOICE_DTX_ENABLED: "${VITE_VOICE_DTX_ENABLED:-true}",
  VITE_VOICE_OPUS_STEREO: "${VITE_VOICE_OPUS_STEREO:-false}",
  VITE_VOICE_OPUS_MIN_PTIME: "${VITE_VOICE_OPUS_MIN_PTIME:-10}",
  VITE_VOICE_OPUS_MAX_PTIME: "${VITE_VOICE_OPUS_MAX_PTIME:-20}",
  VITE_VOICE_OPUS_MAX_PLAYBACK_RATE: "${VITE_VOICE_OPUS_MAX_PLAYBACK_RATE:-48000}",
  VITE_VOICE_VAD_THRESHOLD: "${VITE_VOICE_VAD_THRESHOLD:-0.07}",
  VITE_NOISE_REDUCTION_LEVEL: "${VITE_NOISE_REDUCTION_LEVEL:-0.35}",
  VITE_SCREENSHARE_IDEAL_WIDTH: "${VITE_SCREENSHARE_IDEAL_WIDTH:-1920}",
  VITE_SCREENSHARE_IDEAL_HEIGHT: "${VITE_SCREENSHARE_IDEAL_HEIGHT:-1080}",
  VITE_SCREENSHARE_IDEAL_FPS: "${VITE_SCREENSHARE_IDEAL_FPS:-30}",
  VITE_SCREENSHARE_MAX_FPS: "${VITE_SCREENSHARE_MAX_FPS:-60}",
  VITE_SCREENSHARE_MAX_BITRATE_KBPS: "${VITE_SCREENSHARE_MAX_BITRATE_KBPS:-4000}"
};
EOF

# Execute CMD
exec "$@"
