#!/bin/bash
#
# VPS Deployment Script for RTMP-Disc with Docker Nginx Proxy
# Prerequisites: Docker and Docker Compose already installed
#
# Usage: sudo bash deploy-vps.sh

set -e

echo "========================================"
echo "  RTMP-Disc Deployment"
echo "========================================"
echo ""

# Check if running as root
if [ "$(id -u)" -ne 0 ]; then 
  echo "ERROR: Please run as root (use sudo)"
  exit 1
fi

# Verify Docker is installed
if ! command -v docker > /dev/null 2>&1; then
  echo "ERROR: Docker is not installed. Please install Docker first."
  exit 1
fi

if ! docker compose version > /dev/null 2>&1; then
  echo "ERROR: Docker Compose is not installed. Please install Docker Compose first."
  exit 1
fi

# Get server IP
SERVER_IP=$(hostname -I | awk '{print $1}')
echo "Detected server IP: $SERVER_IP"

# Prompt for domain (optional)
printf "Do you have a domain name? (yes/no): "
read HAS_DOMAIN
if [ "$HAS_DOMAIN" = "yes" ]; then
  printf "Enter your domain (e.g., stream.example.com): "
  read DOMAIN
  
  # With Docker nginx reverse proxy, always use path-based routing
  SERVER_URL="https://$DOMAIN"
  HLS_BASE_URL="https://$DOMAIN/hls"
  API_BASE_URL="https://$DOMAIN"
  CORS_ORIGIN="https://$DOMAIN"
  echo "Using domain with Docker nginx reverse proxy: $DOMAIN"
else
  DOMAIN=$SERVER_IP
  SERVER_URL="http://$SERVER_IP"
  HLS_BASE_URL="http://$SERVER_IP/hls"
  API_BASE_URL="http://$SERVER_IP"
  CORS_ORIGIN="*"
  echo "Using IP address with Docker nginx reverse proxy: $SERVER_IP"
fi

# Navigate to ops directory (assuming script is run from project root)
echo ""
echo "[1/3] Configuring environment..."

if [ ! -d "./ops" ]; then
  echo "ERROR: ops directory not found. Please run this script from the project root."
  exit 1
fi

cd ops

# Check if .env already exists
if [ -f ".env" ]; then
  printf "WARNING: .env file already exists. Overwrite? (yes/no): "
  read OVERWRITE
  if [ "$OVERWRITE" != "yes" ]; then
    echo "Keeping existing .env file. Skipping configuration."
    echo ""
  else
    echo "Creating new .env file..."
    cat > .env <<EOF
# Production Environment Variables
# Generated by deploy-vps.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

NODE_ENV=production

# Security & Sessions
PASSWORD_MIN_LENGTH=8
ACCOUNT_SESSION_TTL_MS=86400000

# Server URLs
SERVER_URL=$SERVER_URL
HLS_BASE_URL=$HLS_BASE_URL
API_BASE_URL=$API_BASE_URL

# CORS Configuration
CORS_ORIGIN=$CORS_ORIGIN

# Resource Limits
MAX_CONNECTIONS_PER_IP=10
MAX_CHANNELS=50
MAX_USERS_PER_CHANNEL=50

# Server Port
PORT=4000
HOST=0.0.0.0

# Deployment Info
DEPLOYED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
SERVER_IP=$SERVER_IP
DOMAIN=$DOMAIN
EOF
    echo "Environment file created"
  fi
else
  echo "Creating .env file..."
  cat > .env <<EOF
# Production Environment Variables
# Generated by deploy-vps.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

NODE_ENV=production

# Security & Sessions
PASSWORD_MIN_LENGTH=8
ACCOUNT_SESSION_TTL_MS=86400000

# Server URLs
SERVER_URL=$SERVER_URL
HLS_BASE_URL=$HLS_BASE_URL
API_BASE_URL=$API_BASE_URL

# CORS Configuration
CORS_ORIGIN=$CORS_ORIGIN

# Resource Limits
MAX_CONNECTIONS_PER_IP=10
MAX_CHANNELS=50
MAX_USERS_PER_CHANNEL=50

# Server Port
PORT=4000
HOST=0.0.0.0

# Deployment Info
DEPLOYED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
SERVER_IP=$SERVER_IP
DOMAIN=$DOMAIN
EOF
  echo "Environment file created"
fi

echo "Environment file created"

# Deploy application
echo ""
echo "[2/3] Building and starting containers..."
docker compose -f docker-compose.prod.yml down 2>/dev/null || true
docker compose -f docker-compose.prod.yml build --no-cache
docker compose -f docker-compose.prod.yml up -d

# Wait for services to start
echo ""
echo "Waiting for services to start..."
sleep 15

# Check service status
echo ""
echo "[3/3] Verifying deployment..."
docker compose -f docker-compose.prod.yml ps

# Display access information
echo ""
echo "========================================"
echo "Deployment Complete!"
echo "========================================"
echo ""
echo "Access your application at:"
if [ "$HAS_DOMAIN" = "yes" ]; then
  echo "  Web Interface: https://$DOMAIN"
  echo "  Backend API: https://$DOMAIN"
  echo "  HLS Streams: https://$DOMAIN/hls"
  echo ""
  echo "Note: Using Docker nginx reverse proxy - web traffic routes through port 80"
  echo "RTMPS ingest terminates on port 443 (suitable for OBS via Cloudflare proxy)"
  echo "If using Cloudflare or similar proxy, set DNS A record to: $SERVER_IP"
else
  echo "  Web Interface: http://$DOMAIN"
  echo "  Backend API: http://$DOMAIN"
  echo "  HLS Streams: http://$DOMAIN/hls"
fi
echo "  RTMP Server: rtmps://$DOMAIN/live"
echo ""
echo "OBS Streaming Setup:"
echo "  Server: rtmps://$DOMAIN/live"
echo "  Stream Key: Generated in app (admin feature)"
echo ""
echo "Useful commands:"
echo "  View logs:    cd ops && docker compose -f docker-compose.prod.yml logs -f"
echo "  Restart:      cd ops && docker compose -f docker-compose.prod.yml restart"
echo "  Stop:         cd ops && docker compose -f docker-compose.prod.yml stop"
echo "  Rebuild:      cd ops && docker compose -f docker-compose.prod.yml up --build -d"
echo ""
echo "========================================"
