#!/bin/bash
#
# VPS Deployment Script for RTMP-Disc with Docker Nginx Proxy
# Prerequisites: Docker and Docker Compose already installed
#
# Usage: sudo bash deploy-vps.sh

set -e

echo "========================================"
echo "  RTMP-Disc Deployment"
echo "========================================"
echo ""

# Check if running as root
if [ "$(id -u)" -ne 0 ]; then 
  echo "ERROR: Please run as root (use sudo)"
  exit 1
fi

# Verify Docker is installed
if ! command -v docker > /dev/null 2>&1; then
  echo "ERROR: Docker is not installed. Please install Docker first."
  exit 1
fi

if ! docker compose version > /dev/null 2>&1; then
  echo "ERROR: Docker Compose is not installed. Please install Docker Compose first."
  exit 1
fi

# Get server IP
SERVER_IP=$(hostname -I | awk '{print $1}')
echo "Detected server IP: $SERVER_IP"

detect_public_ip() {
  local ip=""
  if command -v curl >/dev/null 2>&1; then
    ip=$(curl -s https://api.ipify.org || true)
  fi
  if [ -z "$ip" ] && command -v dig >/dev/null 2>&1; then
    ip=$(dig +short myip.opendns.com @resolver1.opendns.com 2>/dev/null || true)
  fi
  if [ -z "$ip" ] && command -v wget >/dev/null 2>&1; then
    ip=$(wget -qO- https://api.ipify.org || true)
  fi
  echo "$ip"
}

# Prompt for domain (optional)
printf "Do you have a domain name? (yes/no): "
read HAS_DOMAIN
if [ "$HAS_DOMAIN" = "yes" ]; then
  printf "Enter your domain (e.g., stream.example.com): "
  read DOMAIN
  
  # With Docker nginx reverse proxy, always use path-based routing
  SERVER_URL="https://$DOMAIN"
  HLS_BASE_URL="https://$DOMAIN/hls"
  API_BASE_URL="https://$DOMAIN"
  # Include mobile app origins (Capacitor uses https://localhost and capacitor://localhost)
  CORS_ORIGIN="https://$DOMAIN,https://localhost,capacitor://localhost,http://localhost"
  echo "Using domain with Docker nginx reverse proxy: $DOMAIN"
else
  DOMAIN=$SERVER_IP
  SERVER_URL="http://$SERVER_IP"
  HLS_BASE_URL="http://$SERVER_IP/hls"
  API_BASE_URL="http://$SERVER_IP"
  # Include mobile app origins for IP-based deployments
  CORS_ORIGIN="http://$SERVER_IP,https://localhost,capacitor://localhost,http://localhost"
  echo "Using IP address with Docker nginx reverse proxy: $SERVER_IP"
fi

# TURN defaults (override later in ops/.env if needed)
TURN_REALM=${DOMAIN}
TURN_USERNAME="turnuser"

generate_turn_password() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 16
  elif command -v head >/dev/null 2>&1 && command -v od >/dev/null 2>&1; then
    head -c 16 /dev/urandom | od -An -vtx1 | tr -d ' \n'
  else
    date +%s | sha256sum | cut -c1-32
  fi
}

TURN_PASSWORD=$(generate_turn_password)
TURN_URL="turn:${DOMAIN}:3478"

PUBLIC_IP_DETECTED=$(detect_public_ip)
if [ -z "$PUBLIC_IP_DETECTED" ]; then
  PUBLIC_IP_DETECTED="$SERVER_IP"
fi

echo ""
echo "TURN server networking configuration:"
printf "Listening IP (private interface) [%s]: " "$SERVER_IP"
read TURN_LISTENING_IP_INPUT
if [ -z "$TURN_LISTENING_IP_INPUT" ]; then
  TURN_LISTENING_IP="$SERVER_IP"
else
  TURN_LISTENING_IP="$TURN_LISTENING_IP_INPUT"
fi

printf "External/Public IP [%s]: " "$PUBLIC_IP_DETECTED"
read TURN_EXTERNAL_IP_INPUT
if [ -z "$TURN_EXTERNAL_IP_INPUT" ]; then
  TURN_EXTERNAL_IP="$PUBLIC_IP_DETECTED"
else
  TURN_EXTERNAL_IP="$TURN_EXTERNAL_IP_INPUT"
fi

printf "Alternate listening IP (optional, press Enter to skip): "
read TURN_ALT_LISTENING_IP

# Navigate to ops directory (assuming script is run from project root)
echo ""
echo "[1/3] Configuring environment..."

if [ ! -d "./ops" ]; then
  echo "ERROR: ops directory not found. Please run this script from the project root."
  exit 1
fi

cd ops

write_env_file() {
  cat > .env <<EOF
# Production Environment Variables
# Generated by deploy-vps.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

NODE_ENV=production

# Security & Sessions
PASSWORD_MIN_LENGTH=8
ACCOUNT_SESSION_TTL_MS=86400000

# Server URLs
SERVER_URL=$SERVER_URL
HLS_BASE_URL=$HLS_BASE_URL
API_BASE_URL=$API_BASE_URL

# CORS Configuration
CORS_ORIGIN=$CORS_ORIGIN

# Resource Limits
MAX_CONNECTIONS_PER_IP=10
MAX_CHANNELS=50
MAX_USERS_PER_CHANNEL=50

# Server Port
PORT=4000
HOST=0.0.0.0

# TURN / Voice (update credentials as needed)
TURN_REALM=$TURN_REALM
TURN_USERNAME=$TURN_USERNAME
TURN_PASSWORD=$TURN_PASSWORD
TURN_PORT=3478
TURN_MIN_PORT=49160
TURN_MAX_PORT=49200
TURN_LISTENING_IP=$TURN_LISTENING_IP
TURN_ALT_LISTENING_IP=$TURN_ALT_LISTENING_IP
TURN_EXTERNAL_IP=$TURN_EXTERNAL_IP
TURN_EXTRA_ARGS=
VITE_TURN_URL=$TURN_URL
VITE_TURN_USERNAME=$TURN_USERNAME
VITE_TURN_CREDENTIAL=$TURN_PASSWORD
VITE_VOICE_OPUS_BITRATE=64000
VITE_VOICE_DTX_ENABLED=true
VITE_VOICE_OPUS_STEREO=false
VITE_VOICE_OPUS_MIN_PTIME=10
VITE_VOICE_OPUS_MAX_PTIME=20
VITE_VOICE_OPUS_MAX_PLAYBACK_RATE=48000
VITE_VOICE_VAD_THRESHOLD=0.07

# Deployment Info
DEPLOYED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
SERVER_IP=$SERVER_IP
DOMAIN=$DOMAIN
EOF
  echo "Environment file created"
}

# Check if .env already exists
if [ -f ".env" ]; then
  printf "WARNING: .env file already exists. Overwrite? (yes/no): "
  read OVERWRITE
  if [ "$OVERWRITE" != "yes" ]; then
    echo "Keeping existing .env file. Skipping configuration."
    echo ""
  else
    echo "Creating new .env file..."
    write_env_file
  fi
else
  echo "Creating .env file..."
  write_env_file
fi

# Deploy application
echo ""
echo "[2/3] Building and starting containers..."
docker compose -f docker-compose.prod.yml down 2>/dev/null || true
docker compose -f docker-compose.prod.yml build --no-cache
docker compose -f docker-compose.prod.yml up -d

# Wait for services to start
echo ""
echo "Waiting for services to start..."
sleep 15

# Check service status
echo ""
echo "[3/3] Verifying deployment..."
docker compose -f docker-compose.prod.yml ps

# Display access information
echo ""
echo "========================================"
echo "Deployment Complete!"
echo "========================================"
echo ""
echo "Access your application at:"
if [ "$HAS_DOMAIN" = "yes" ]; then
  echo "  Web Interface: https://$DOMAIN"
  echo "  Backend API: https://$DOMAIN"
  echo "  HLS Streams: https://$DOMAIN/hls"
  echo ""
  echo "Note: Using Docker nginx reverse proxy - web traffic routes through port 80"
  echo "Ensure RTMP port 1935 is reachable (direct or via proxy)"
  echo "If using Cloudflare or similar proxy, set DNS A record to: $SERVER_IP"
else
  echo "  Web Interface: http://$DOMAIN"
  echo "  Backend API: http://$DOMAIN"
  echo "  HLS Streams: http://$DOMAIN/hls"
fi
echo "  RTMP Server: rtmp://$DOMAIN/live"
echo ""
echo "OBS Streaming Setup:"
echo "  Server: rtmp://$DOMAIN/live"
echo "  Stream Key: Generated in app (admin feature)"
echo ""
echo "Useful commands:"
echo "  View logs:    cd ops && docker compose -f docker-compose.prod.yml logs -f"
echo "  Restart:      cd ops && docker compose -f docker-compose.prod.yml restart"
echo "  Stop:         cd ops && docker compose -f docker-compose.prod.yml stop"
echo "  Rebuild:      cd ops && docker compose -f docker-compose.prod.yml up --build -d"
echo ""
echo "========================================"
