#!/usr/bin/env pwsh
<#!
.SYNOPSIS
Builds the Datasetto web client for mobile and syncs the Android Capacitor project.

.DESCRIPTION
Installs npm dependencies (optional), builds the Vite web bundle with production/mobile
endpoints, then copies assets into the Android platform via `npx cap sync android`.

.PARAMETER ForceInstall
Always run `npm install` in both client/ and mobile/ workspaces, even if node_modules exists.

.EXAMPLE
./deploy-mobile.ps1

.EXAMPLE
./deploy-mobile.ps1 -ForceInstall
#>
param(
  [switch]$ForceInstall,
  [switch]$Help
)

if ($Help) {
  Get-Help -Detailed -ErrorAction SilentlyContinue
  if ($LASTEXITCODE -ne 0) {
    Write-Host "Usage: ./deploy-mobile.ps1 [-ForceInstall]" -ForegroundColor Yellow
  }
  exit 0
}

$ErrorActionPreference = 'Stop'

function Resolve-PathSafe {
  param([string]$Path)
  return (Resolve-Path -Path $Path -ErrorAction Stop).ProviderPath
}

$projectRoot = Resolve-PathSafe (Split-Path -Parent $MyInvocation.MyCommand.Path)
$clientDir   = Join-Path $projectRoot 'client'
$mobileDir   = Join-Path $projectRoot 'mobile'
$opsEnv      = Join-Path $projectRoot 'ops/.env'
$clientMobileEnv = Join-Path $clientDir '.env.mobile'
$clientProdEnv   = Join-Path $clientDir '.env.production'

function Assert-Directory {
  param([string]$Path)
  if (-not (Test-Path -Path $Path -PathType Container)) {
    throw "[deploy-mobile] Required directory missing: $Path"
  }
}

Assert-Directory $clientDir
Assert-Directory $mobileDir

if (-not (Get-Command npm -ErrorAction SilentlyContinue)) {
  throw '[deploy-mobile] npm not found in PATH. Please install Node.js first.'
}

# Check if ops/.env exists to extract production URLs
if (Test-Path $opsEnv) {
  Write-Host '[deploy-mobile] Found ops/.env, extracting URLs for mobile build...' -ForegroundColor Cyan
  
  # Parse ops/.env for backend URLs
  $opsContent = Get-Content $opsEnv -Raw
  $serverUrl = if ($opsContent -match '(?m)^SERVER_URL=(.+)$') { $Matches[1].Trim() } else { 'https://datasetto.com' }
  $hlsUrl = if ($opsContent -match '(?m)^HLS_BASE_URL=(.+)$') { $Matches[1].Trim() } else { "$serverUrl/hls" }
  $rtmpUrl = if ($opsContent -match '(?m)^RTMP_SERVER_URL=(.+)$') { $Matches[1].Trim() } else { "rtmp://datasetto.com:1935/hls" }
  
  # Generate client/.env.mobile
  Write-Host "[deploy-mobile] Creating $clientMobileEnv with production URLs..." -ForegroundColor Green
  @"
# Environment variables for mobile builds (Android/iOS)
# Auto-generated by deploy-mobile.ps1 on $(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')

# Backend WebSocket/API server
VITE_SERVER_URL=$serverUrl

# HLS streaming endpoint
VITE_HLS_BASE_URL=$hlsUrl

# API endpoint
VITE_API_BASE_URL=$serverUrl

# RTMP server URL
VITE_RTMP_SERVER_URL=$rtmpUrl

# Mobile default server (fallback)
VITE_MOBILE_DEFAULT_SERVER_URL=$serverUrl
"@ | Set-Content -Path $clientMobileEnv -NoNewline

  Write-Host "[deploy-mobile] Mobile environment configured: $serverUrl" -ForegroundColor Green
}
elseif (-not (Test-Path $clientMobileEnv) -and -not (Test-Path $clientProdEnv)) {
  Write-Warning '[deploy-mobile] No environment file detected. Build will fall back to localhost URLs.'
  Write-Host '  Run deploy-vps.sh first to generate ops/.env, or manually create client/.env.mobile'
}

foreach ($entry in @(
  @{ Dir = $clientDir; Name = 'client' },
  @{ Dir = $mobileDir; Name = 'mobile' }
)) {
  Push-Location $entry.Dir
  try {
    if ($ForceInstall -or -not (Test-Path 'node_modules' -PathType Container)) {
      Write-Host "[deploy-mobile] Installing $($entry.Name) dependencies..." -ForegroundColor Cyan
      npm install
    }
    else {
      Write-Host "[deploy-mobile] $($entry.Name) dependencies already present; skipping npm install." -ForegroundColor DarkGray
    }
  }
  finally {
    Pop-Location
  }
}

Push-Location $mobileDir
try {
  Write-Host '[deploy-mobile] Building web assets for mobile...' -ForegroundColor Cyan
  npm run build:web

  Write-Host '[deploy-mobile] Syncing Android platform...' -ForegroundColor Cyan
  npx cap sync android
}
finally {
  Pop-Location
}

Write-Host ''
Write-Host '[deploy-mobile] Android assets refreshed. Open Android Studio with:' -ForegroundColor Green
Write-Host '  cd mobile; npm run open:android' -ForegroundColor Green
